spring.application.name=ferreteria
server.port=8080

# Configuracion de la db
spring.datasource.url=jdbc:mysql:://localhost:3306/db_ferreteria # Conectividad y tipo
spring.datasource.username=root
spring.datasource.password=usuario01%
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-plataform=org.hibernate.dialect.MySQLDialect # Permite hacer relaciones entre tablas, restricciones ...
spring.jpa.show-sql=true # Si queremos que aparezcan o no las sentencias SQL en consola